apiVersion: v3
name: exaterulesapi
version: 1.0.1
description: An Exate Rules WebApi Core application deployment
home: https://dev.azure.com/exatetechnology/exatetechnology/_git/exate.rules.core
sources:
  - https://dev.azure.com/exatetechnology/exatetechnology/_git/exate.rules.core
maintainers:
  - name: Exate
    email: zeeshan@exate.com