apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Chart.Name }}"
    heritage: "{{ .Release.Service }}"
stringData:
  DB_SECOWSER_PASSWORD: {{ .Values.db.DB_SECOWSER_PASSWORD }}
  DB_CACHE_PASSWORD: {{ .Values.db.DB_CACHE_PASSWORD }}
  COMMUNICATION__RABBITMQ__PASSWORD: {{  .Values.rabbitMQ.password }}
