apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Chart.Name }}
    namespace: {{ .Values.namespace }}
    labels:
      app: {{ .Chart.Name }}
      release: "{{ .Chart.Name }}"
      heritage: {{ .Release.Service }}
      chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.config.ASPNETCORE_ENVIRONMENT }}
  BUILD_VERSION: {{ .Values.config.BUILD_VERSION}}
  ISSUER_URL: {{ .Values.config.ISSUER_URL }}
  ALLOWED_ORIGINS__0: {{ .Values.config.ALLOWED_ORIGINS__0 }}
  ALLOWED_ORIGINS__1: {{ .Values.config.ALLOWED_ORIGINS__1 }}
  #ALLOWED_ORIGINS__2: {{ .Values.config.ALLOWED_ORIGINS__2 }}
  DB_DATA_SOURCE: {{ .Values.config.DB_DATA_SOURCE }}
  DB_INITIAL_CATALOG: {{ .Values.config.DB_INITIAL_CATALOG }}
  DB_USER_ID: {{ .Values.config.DB_USER_ID }}
  SERILOG__WRITETO__0__ARGS__SERVERURL: {{ .Values.config.SERILOG__WRITETO__0__ARGS__SERVERURL }}