apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Chart.Name }}
    namespace: {{ .Values.namespace }}
    labels:
      app: {{ .Chart.Name }}
      release: "{{ .Chart.Name }}"
      heritage: {{ .Release.Service }}
      chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.config.ASPNETCORE_ENVIRONMENT }}
  APP_NAME: {{ .Values.config.APP_NAME }}
  BUILD_VERSION: {{ .Values.config.BUILD_VERSION }}
  ALLOWED_ORIGINS__0: http://localhost:4200
  ALLOWED_ORIGINS__1: https://localhost:4200
  ALLOWED_ORIGINS__2: "{{ .Values.config.ALLOWED_ORIGINS__2 }}"
  DB_SECOWSER_DATA_SOURCE: "{{ .Values.config.DB_SECOWSER_DATA_SOURCE }}"
  DB_SECOWSER_INITIAL_CATALOG: "{{ .Values.config.DB_SECOWSER_INITIAL_CATALOG }}"
  DB_SECOWSER_USER_ID: {{ .Values.config.DB_SECOWSER_USER_ID }}
  DB_CACHE_DATA_SOURCE: "{{ .Values.config.DB_CACHE_DATA_SOURCE }}"
  DB_CACHE_INITIAL_CATALOG: "{{ .Values.config.DB_CACHE_INITIAL_CATALOG }}"
  DB_CACHE_USER_ID: {{ .Values.config.DB_CACHE_USER_ID }}
  SERILOG__WRITETO__0__ARGS__SERVERURL: "{{ .Values.config.SERILOG__WRITETO__0__ARGS__SERVERURL }}"
  EXATE__ENDPOINTS__AUTHURL: "{{ .Values.config.EXATE__ENDPOINTS__AUTHURL }}"
  EXATE__ENDPOINTS__MANIFESTAPI: "{{ .Values.config.EXATE__ENDPOINTS__MANIFESTAPI }}"
  COMMUNICATION__RABBITMQ__HOST: "{{ .Values.config.COMMUNICATION__RABBITMQ__HOST }}"
  COMMUNICATION__RABBITMQ__PORT: "{{ .Values.config.COMMUNICATION__RABBITMQ__PORT }}"
  COMMUNICATION__RABBITMQ__USERNAME: {{ .Values.config.COMMUNICATION__RABBITMQ__USERNAME }}

