apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    release: "{{ .Chart.Name }}"
    heritage: {{ .Release.Service }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        release: "{{ .Chart.Name }}"
        heritage: {{ .Release.Service }}
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: dockerlogin
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.dockerImage }}
          imagePullPolicy: {{  .Values.image.pullPolicy }}
          command: ["dotnet", "Ex8.EtlApi.dll"]
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}
          env:
            - name: DB_SECOWSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: db.secowser.password
            - name: DB_CACHE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db.cache.password
                  name: {{ .Chart.Name }}
            - name: COMMUNICATION__RABBITMQ__PASSWORD
              valueFrom:
                secretKeyRef:
                  key: rabbitMQ.password
                  name: {{ .Chart.Name }}
          args: ["-logtostderr", "true"]
          ports:
            - containerPort: 80
            - containerPort: 443
          resources:
            requests:
              cpu: {{ .Values.resources.cpu }}
              memory: {{ .Values.resources.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}











