apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Chart.Name }}"
    heritage: "{{ .Release.Service }}"
stringData:
  db.password: {{ .Values.db.DB_PASSWORD }}
  rabbitMQ.password: {{ .Values.rabbitMQ.COMMUNICATION__RABBITMQ__PASSWORD }}
