apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Chart.Name }}"
    heritage: "{{ .Release.Service }}"
stringData:
  db.DB__AUTH__PASSWORD: {{ required "A value is required for db.auth.password" .Values.db.DB__AUTH__PASSWORD }}
  db.DB__EXATE__PASSWORD: {{ required "A value is required for db.exate.password" .Values.db.DB__EXATE__PASSWORD }}
